#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🎃🎃🎃start lint-staged ==============================="

npx --no-install lint-staged

echo "🎉🎉🎉end lint-staged ==============================="

echo "🎃🎃🎃start pretty-quick ==============================="

# pnpm run lint:fix
npx pretty-quick --staged

echo "🎉🎉🎉end pretty-quick ==============================="
